name: Deploy to prod

concurrency: 1

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.AZ_DEV_DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
      - uses: databricks/setup-cli@main
      - run: databricks bundle run example_notebook_job -t prod --refresh-all
        env:
          DATABRICKS_TOKEN: ${{ secrets.AZ_DEV_DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
